/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedWorkbenchRouteImport } from "./routes/_authenticated/workbench"
import { Route as AuthenticatedWikiRouteImport } from "./routes/_authenticated/wiki"
import { Route as AuthenticatedTestingRouteImport } from "./routes/_authenticated/testing"
import { Route as AuthenticatedTeamGovernanceRouteImport } from "./routes/_authenticated/team-governance"
import { Route as AuthenticatedStandardsReviewRouteImport } from "./routes/_authenticated/standards-review"
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings"
import { Route as AuthenticatedSecurityRouteImport } from "./routes/_authenticated/security"
import { Route as AuthenticatedRequirementsRouteImport } from "./routes/_authenticated/requirements"
import { Route as AuthenticatedRentgenRouteImport } from "./routes/_authenticated/rentgen"
import { Route as AuthenticatedReleaseReadinessRouteImport } from "./routes/_authenticated/release-readiness"
import { Route as AuthenticatedQualityRouteImport } from "./routes/_authenticated/quality"
import { Route as AuthenticatedOperationsRouteImport } from "./routes/_authenticated/operations"
import { Route as AuthenticatedOfflineReadinessRouteImport } from "./routes/_authenticated/offline-readiness"
import { Route as AuthenticatedMetadataRouteImport } from "./routes/_authenticated/metadata"
import { Route as AuthenticatedMarketplaceRouteImport } from "./routes/_authenticated/marketplace"
import { Route as AuthenticatedIdeRouteImport } from "./routes/_authenticated/ide"
import { Route as AuthenticatedFormsRouteImport } from "./routes/_authenticated/forms"
import { Route as AuthenticatedEdtMcpRouteImport } from "./routes/_authenticated/edt-mcp"
import { Route as AuthenticatedCopilotCoverageRouteImport } from "./routes/_authenticated/copilot-coverage"
import { Route as AuthenticatedCopilotRouteImport } from "./routes/_authenticated/copilot"
import { Route as AuthenticatedCodeReviewRouteImport } from "./routes/_authenticated/code-review"
import { Route as AuthenticatedChangeRouteImport } from "./routes/_authenticated/change"
import { Route as AuthenticatedBpmnRouteImport } from "./routes/_authenticated/bpmn"
import { Route as AuthenticatedArchitectureRouteImport } from "./routes/_authenticated/architecture"
import { Route as AuthenticatedAdminRouteImport } from "./routes/_authenticated/admin"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkbenchRoute = AuthenticatedWorkbenchRouteImport.update({
  id: "/workbench",
  path: "/workbench",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWikiRoute = AuthenticatedWikiRouteImport.update({
  id: "/wiki",
  path: "/wiki",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestingRoute = AuthenticatedTestingRouteImport.update({
  id: "/testing",
  path: "/testing",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamGovernanceRoute =
  AuthenticatedTeamGovernanceRouteImport.update({
    id: "/team-governance",
    path: "/team-governance",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStandardsReviewRoute =
  AuthenticatedStandardsReviewRouteImport.update({
    id: "/standards-review",
    path: "/standards-review",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: "/security",
  path: "/security",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequirementsRoute =
  AuthenticatedRequirementsRouteImport.update({
    id: "/requirements",
    path: "/requirements",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRentgenRoute = AuthenticatedRentgenRouteImport.update({
  id: "/rentgen",
  path: "/rentgen",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReleaseReadinessRoute =
  AuthenticatedReleaseReadinessRouteImport.update({
    id: "/release-readiness",
    path: "/release-readiness",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: "/quality",
  path: "/quality",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfflineReadinessRoute =
  AuthenticatedOfflineReadinessRouteImport.update({
    id: "/offline-readiness",
    path: "/offline-readiness",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMetadataRoute = AuthenticatedMetadataRouteImport.update({
  id: "/metadata",
  path: "/metadata",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: "/marketplace",
    path: "/marketplace",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIdeRoute = AuthenticatedIdeRouteImport.update({
  id: "/ide",
  path: "/ide",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: "/forms",
  path: "/forms",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEdtMcpRoute = AuthenticatedEdtMcpRouteImport.update({
  id: "/edt-mcp",
  path: "/edt-mcp",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotCoverageRoute =
  AuthenticatedCopilotCoverageRouteImport.update({
    id: "/copilot-coverage",
    path: "/copilot-coverage",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: "/copilot",
  path: "/copilot",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodeReviewRoute = AuthenticatedCodeReviewRouteImport.update({
  id: "/code-review",
  path: "/code-review",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangeRoute = AuthenticatedChangeRouteImport.update({
  id: "/change",
  path: "/change",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBpmnRoute = AuthenticatedBpmnRouteImport.update({
  id: "/bpmn",
  path: "/bpmn",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchitectureRoute =
  AuthenticatedArchitectureRouteImport.update({
    id: "/architecture",
    path: "/architecture",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof LoginRoute
  "/admin": typeof AuthenticatedAdminRoute
  "/architecture": typeof AuthenticatedArchitectureRoute
  "/bpmn": typeof AuthenticatedBpmnRoute
  "/change": typeof AuthenticatedChangeRoute
  "/code-review": typeof AuthenticatedCodeReviewRoute
  "/copilot": typeof AuthenticatedCopilotRoute
  "/copilot-coverage": typeof AuthenticatedCopilotCoverageRoute
  "/edt-mcp": typeof AuthenticatedEdtMcpRoute
  "/forms": typeof AuthenticatedFormsRoute
  "/ide": typeof AuthenticatedIdeRoute
  "/marketplace": typeof AuthenticatedMarketplaceRoute
  "/metadata": typeof AuthenticatedMetadataRoute
  "/offline-readiness": typeof AuthenticatedOfflineReadinessRoute
  "/operations": typeof AuthenticatedOperationsRoute
  "/quality": typeof AuthenticatedQualityRoute
  "/release-readiness": typeof AuthenticatedReleaseReadinessRoute
  "/rentgen": typeof AuthenticatedRentgenRoute
  "/requirements": typeof AuthenticatedRequirementsRoute
  "/security": typeof AuthenticatedSecurityRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/standards-review": typeof AuthenticatedStandardsReviewRoute
  "/team-governance": typeof AuthenticatedTeamGovernanceRoute
  "/testing": typeof AuthenticatedTestingRoute
  "/wiki": typeof AuthenticatedWikiRoute
  "/workbench": typeof AuthenticatedWorkbenchRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/admin": typeof AuthenticatedAdminRoute
  "/architecture": typeof AuthenticatedArchitectureRoute
  "/bpmn": typeof AuthenticatedBpmnRoute
  "/change": typeof AuthenticatedChangeRoute
  "/code-review": typeof AuthenticatedCodeReviewRoute
  "/copilot": typeof AuthenticatedCopilotRoute
  "/copilot-coverage": typeof AuthenticatedCopilotCoverageRoute
  "/edt-mcp": typeof AuthenticatedEdtMcpRoute
  "/forms": typeof AuthenticatedFormsRoute
  "/ide": typeof AuthenticatedIdeRoute
  "/marketplace": typeof AuthenticatedMarketplaceRoute
  "/metadata": typeof AuthenticatedMetadataRoute
  "/offline-readiness": typeof AuthenticatedOfflineReadinessRoute
  "/operations": typeof AuthenticatedOperationsRoute
  "/quality": typeof AuthenticatedQualityRoute
  "/release-readiness": typeof AuthenticatedReleaseReadinessRoute
  "/rentgen": typeof AuthenticatedRentgenRoute
  "/requirements": typeof AuthenticatedRequirementsRoute
  "/security": typeof AuthenticatedSecurityRoute
  "/settings": typeof AuthenticatedSettingsRoute
  "/standards-review": typeof AuthenticatedStandardsReviewRoute
  "/team-governance": typeof AuthenticatedTeamGovernanceRoute
  "/testing": typeof AuthenticatedTestingRoute
  "/wiki": typeof AuthenticatedWikiRoute
  "/workbench": typeof AuthenticatedWorkbenchRoute
  "/": typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/login": typeof LoginRoute
  "/_authenticated/admin": typeof AuthenticatedAdminRoute
  "/_authenticated/architecture": typeof AuthenticatedArchitectureRoute
  "/_authenticated/bpmn": typeof AuthenticatedBpmnRoute
  "/_authenticated/change": typeof AuthenticatedChangeRoute
  "/_authenticated/code-review": typeof AuthenticatedCodeReviewRoute
  "/_authenticated/copilot": typeof AuthenticatedCopilotRoute
  "/_authenticated/copilot-coverage": typeof AuthenticatedCopilotCoverageRoute
  "/_authenticated/edt-mcp": typeof AuthenticatedEdtMcpRoute
  "/_authenticated/forms": typeof AuthenticatedFormsRoute
  "/_authenticated/ide": typeof AuthenticatedIdeRoute
  "/_authenticated/marketplace": typeof AuthenticatedMarketplaceRoute
  "/_authenticated/metadata": typeof AuthenticatedMetadataRoute
  "/_authenticated/offline-readiness": typeof AuthenticatedOfflineReadinessRoute
  "/_authenticated/operations": typeof AuthenticatedOperationsRoute
  "/_authenticated/quality": typeof AuthenticatedQualityRoute
  "/_authenticated/release-readiness": typeof AuthenticatedReleaseReadinessRoute
  "/_authenticated/rentgen": typeof AuthenticatedRentgenRoute
  "/_authenticated/requirements": typeof AuthenticatedRequirementsRoute
  "/_authenticated/security": typeof AuthenticatedSecurityRoute
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute
  "/_authenticated/standards-review": typeof AuthenticatedStandardsReviewRoute
  "/_authenticated/team-governance": typeof AuthenticatedTeamGovernanceRoute
  "/_authenticated/testing": typeof AuthenticatedTestingRoute
  "/_authenticated/wiki": typeof AuthenticatedWikiRoute
  "/_authenticated/workbench": typeof AuthenticatedWorkbenchRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/admin"
    | "/architecture"
    | "/bpmn"
    | "/change"
    | "/code-review"
    | "/copilot"
    | "/copilot-coverage"
    | "/edt-mcp"
    | "/forms"
    | "/ide"
    | "/marketplace"
    | "/metadata"
    | "/offline-readiness"
    | "/operations"
    | "/quality"
    | "/release-readiness"
    | "/rentgen"
    | "/requirements"
    | "/security"
    | "/settings"
    | "/standards-review"
    | "/team-governance"
    | "/testing"
    | "/wiki"
    | "/workbench"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/admin"
    | "/architecture"
    | "/bpmn"
    | "/change"
    | "/code-review"
    | "/copilot"
    | "/copilot-coverage"
    | "/edt-mcp"
    | "/forms"
    | "/ide"
    | "/marketplace"
    | "/metadata"
    | "/offline-readiness"
    | "/operations"
    | "/quality"
    | "/release-readiness"
    | "/rentgen"
    | "/requirements"
    | "/security"
    | "/settings"
    | "/standards-review"
    | "/team-governance"
    | "/testing"
    | "/wiki"
    | "/workbench"
    | "/"
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/admin"
    | "/_authenticated/architecture"
    | "/_authenticated/bpmn"
    | "/_authenticated/change"
    | "/_authenticated/code-review"
    | "/_authenticated/copilot"
    | "/_authenticated/copilot-coverage"
    | "/_authenticated/edt-mcp"
    | "/_authenticated/forms"
    | "/_authenticated/ide"
    | "/_authenticated/marketplace"
    | "/_authenticated/metadata"
    | "/_authenticated/offline-readiness"
    | "/_authenticated/operations"
    | "/_authenticated/quality"
    | "/_authenticated/release-readiness"
    | "/_authenticated/rentgen"
    | "/_authenticated/requirements"
    | "/_authenticated/security"
    | "/_authenticated/settings"
    | "/_authenticated/standards-review"
    | "/_authenticated/team-governance"
    | "/_authenticated/testing"
    | "/_authenticated/wiki"
    | "/_authenticated/workbench"
    | "/_authenticated/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/workbench": {
      id: "/_authenticated/workbench"
      path: "/workbench"
      fullPath: "/workbench"
      preLoaderRoute: typeof AuthenticatedWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/wiki": {
      id: "/_authenticated/wiki"
      path: "/wiki"
      fullPath: "/wiki"
      preLoaderRoute: typeof AuthenticatedWikiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/testing": {
      id: "/_authenticated/testing"
      path: "/testing"
      fullPath: "/testing"
      preLoaderRoute: typeof AuthenticatedTestingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/team-governance": {
      id: "/_authenticated/team-governance"
      path: "/team-governance"
      fullPath: "/team-governance"
      preLoaderRoute: typeof AuthenticatedTeamGovernanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/standards-review": {
      id: "/_authenticated/standards-review"
      path: "/standards-review"
      fullPath: "/standards-review"
      preLoaderRoute: typeof AuthenticatedStandardsReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/settings": {
      id: "/_authenticated/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/security": {
      id: "/_authenticated/security"
      path: "/security"
      fullPath: "/security"
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/requirements": {
      id: "/_authenticated/requirements"
      path: "/requirements"
      fullPath: "/requirements"
      preLoaderRoute: typeof AuthenticatedRequirementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/rentgen": {
      id: "/_authenticated/rentgen"
      path: "/rentgen"
      fullPath: "/rentgen"
      preLoaderRoute: typeof AuthenticatedRentgenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/release-readiness": {
      id: "/_authenticated/release-readiness"
      path: "/release-readiness"
      fullPath: "/release-readiness"
      preLoaderRoute: typeof AuthenticatedReleaseReadinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/quality": {
      id: "/_authenticated/quality"
      path: "/quality"
      fullPath: "/quality"
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/operations": {
      id: "/_authenticated/operations"
      path: "/operations"
      fullPath: "/operations"
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/offline-readiness": {
      id: "/_authenticated/offline-readiness"
      path: "/offline-readiness"
      fullPath: "/offline-readiness"
      preLoaderRoute: typeof AuthenticatedOfflineReadinessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/metadata": {
      id: "/_authenticated/metadata"
      path: "/metadata"
      fullPath: "/metadata"
      preLoaderRoute: typeof AuthenticatedMetadataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/marketplace": {
      id: "/_authenticated/marketplace"
      path: "/marketplace"
      fullPath: "/marketplace"
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/ide": {
      id: "/_authenticated/ide"
      path: "/ide"
      fullPath: "/ide"
      preLoaderRoute: typeof AuthenticatedIdeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/forms": {
      id: "/_authenticated/forms"
      path: "/forms"
      fullPath: "/forms"
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/edt-mcp": {
      id: "/_authenticated/edt-mcp"
      path: "/edt-mcp"
      fullPath: "/edt-mcp"
      preLoaderRoute: typeof AuthenticatedEdtMcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/copilot-coverage": {
      id: "/_authenticated/copilot-coverage"
      path: "/copilot-coverage"
      fullPath: "/copilot-coverage"
      preLoaderRoute: typeof AuthenticatedCopilotCoverageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/copilot": {
      id: "/_authenticated/copilot"
      path: "/copilot"
      fullPath: "/copilot"
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/code-review": {
      id: "/_authenticated/code-review"
      path: "/code-review"
      fullPath: "/code-review"
      preLoaderRoute: typeof AuthenticatedCodeReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/change": {
      id: "/_authenticated/change"
      path: "/change"
      fullPath: "/change"
      preLoaderRoute: typeof AuthenticatedChangeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/bpmn": {
      id: "/_authenticated/bpmn"
      path: "/bpmn"
      fullPath: "/bpmn"
      preLoaderRoute: typeof AuthenticatedBpmnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/architecture": {
      id: "/_authenticated/architecture"
      path: "/architecture"
      fullPath: "/architecture"
      preLoaderRoute: typeof AuthenticatedArchitectureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/admin": {
      id: "/_authenticated/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArchitectureRoute: typeof AuthenticatedArchitectureRoute
  AuthenticatedBpmnRoute: typeof AuthenticatedBpmnRoute
  AuthenticatedChangeRoute: typeof AuthenticatedChangeRoute
  AuthenticatedCodeReviewRoute: typeof AuthenticatedCodeReviewRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedCopilotCoverageRoute: typeof AuthenticatedCopilotCoverageRoute
  AuthenticatedEdtMcpRoute: typeof AuthenticatedEdtMcpRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedIdeRoute: typeof AuthenticatedIdeRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMetadataRoute: typeof AuthenticatedMetadataRoute
  AuthenticatedOfflineReadinessRoute: typeof AuthenticatedOfflineReadinessRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReleaseReadinessRoute: typeof AuthenticatedReleaseReadinessRoute
  AuthenticatedRentgenRoute: typeof AuthenticatedRentgenRoute
  AuthenticatedRequirementsRoute: typeof AuthenticatedRequirementsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStandardsReviewRoute: typeof AuthenticatedStandardsReviewRoute
  AuthenticatedTeamGovernanceRoute: typeof AuthenticatedTeamGovernanceRoute
  AuthenticatedTestingRoute: typeof AuthenticatedTestingRoute
  AuthenticatedWikiRoute: typeof AuthenticatedWikiRoute
  AuthenticatedWorkbenchRoute: typeof AuthenticatedWorkbenchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArchitectureRoute: AuthenticatedArchitectureRoute,
  AuthenticatedBpmnRoute: AuthenticatedBpmnRoute,
  AuthenticatedChangeRoute: AuthenticatedChangeRoute,
  AuthenticatedCodeReviewRoute: AuthenticatedCodeReviewRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedCopilotCoverageRoute: AuthenticatedCopilotCoverageRoute,
  AuthenticatedEdtMcpRoute: AuthenticatedEdtMcpRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedIdeRoute: AuthenticatedIdeRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMetadataRoute: AuthenticatedMetadataRoute,
  AuthenticatedOfflineReadinessRoute: AuthenticatedOfflineReadinessRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReleaseReadinessRoute: AuthenticatedReleaseReadinessRoute,
  AuthenticatedRentgenRoute: AuthenticatedRentgenRoute,
  AuthenticatedRequirementsRoute: AuthenticatedRequirementsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStandardsReviewRoute: AuthenticatedStandardsReviewRoute,
  AuthenticatedTeamGovernanceRoute: AuthenticatedTeamGovernanceRoute,
  AuthenticatedTestingRoute: AuthenticatedTestingRoute,
  AuthenticatedWikiRoute: AuthenticatedWikiRoute,
  AuthenticatedWorkbenchRoute: AuthenticatedWorkbenchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
