"""Passive, opt-in byte recorder for the existing input-core Python regressions.

No child launch, signal, wait, authorization bypass, or archive-path read. Only
bytes already generated by fixtures or transferred by RustInputSession are
retained. Run after source review with RENTGEN_INPUT_CORE_CAPTURE_DIR pointing
outside the checkout. The original assertions and process ownership stay intact.
"""
import hashlib
import json
import os
from pathlib import Path


class Capture:
    def __init__(self, directory, nodeid, module):
        root = Path(directory).resolve(strict=True)
        checkout = Path(module.__file__).resolve().parents[2]
        if root.is_relative_to(checkout):
            raise ValueError("Input-core captures must remain outside the checkout")
        self.directory = root / hashlib.sha256(nodeid.encode()).hexdigest()[:20]
        self.directory.mkdir(exist_ok=False)
        self.nodeid, self.sessions, self.files = nodeid, [], {}
        self.events, self.generated, self.cli_calls = [], [], []
        self.capture_failure = None  # Latched once; expected product errors cannot clear it.
        self.byte_count = 0
        self.source_pin = hashlib.sha256(Path(module.__file__).read_bytes()).hexdigest()
        self.product_pin = hashlib.sha256(Path(module.rust_input.__file__).read_bytes()).hexdigest()

    def failed(self, stage, error):
        if self.capture_failure is None:
            self.capture_failure = {"stage": stage, "exception_type": type(error).__name__}

    def append(self, name, data):
        try:
            data = bytes(data)
            self.byte_count += len(data)
            if self.byte_count > 256 * 1024 * 1024:
                raise RuntimeError("Finite input-core capture byte cap exceeded")
            with (self.directory / name).open("ab") as out:
                if out.write(data) != len(data):
                    raise RuntimeError("Input-core capture short write")
            self.files[name] = True
        except BaseException as error:
            # A failure after a real pipe read/write may be translated by the
            # product into an INPUT_CORE_* error expected by a negative test.
            # Preserve independent recorder failure for fixture teardown.
            self.failed("append", error)
            raise

    def session(self, owner):
        for index, item in enumerate(self.sessions):
            if item is owner:
                return index
        self.sessions.append(owner)
        index = len(self.sessions) - 1
        for role in ("stdin", "stdout", "stderr"):
            self.append(f"session-{index:03}-{role}.bin", b"")
        return index

    def stream(self, fd):
        for index, owner in enumerate(self.sessions):
            if owner.process is None:
                continue
            for role in ("stdin", "stdout", "stderr"):
                stream = getattr(owner.process, role)
                if stream is not None and not stream.closed and stream.fileno() == fd:
                    return index, role
        return None

    def transferred(self, operation, fd, data):
        try:
            match = self.stream(fd)
            if match is not None:
                index, role = match
                if (operation == "write") != (role == "stdin"):
                    raise AssertionError("Unexpected input-core capture pipe direction")
                self.append(f"session-{index:03}-{role}.bin", data)
                self.events.append({"session": index, "operation": operation, "stream": role, "bytes": len(data)})
        except BaseException as error:
            self.failed("pipe_capture", error)
            raise

    def fixture(self, kind, raw, **metadata):
        try:
            number = len(self.generated)
            name = f"generated-{number:03}-{kind}.bin"
            self.append(name, raw)
            self.generated.append({"kind": kind, "file": name, **metadata})
        except BaseException as error:
            self.failed("fixture_capture", error)
            raise

    def finish(self):
        try:
            self.write_manifest()
        except BaseException as error:
            self.failed("manifest", error)
            raise
        finally:
            # This runs outside the test call, including when it accepted an
            # expected CoreError that masked an earlier recorder I/O failure.
            if self.capture_failure is not None:
                raise RuntimeError("Input-core regression capture failed") from None

    def write_manifest(self):
        manifest = {
            "schema": 1, "nodeid": self.nodeid, "test_source_sha256": self.source_pin,
            "product_source_sha256": self.product_pin,
            "recorder_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
            "capture_status": "failed" if self.capture_failure is not None else "recorded_with_scope_limits",
            "capture_failure": self.capture_failure,
            "wire_capture_scope": "in_process_sessions_only",
            "in_process_session_observed": bool(self.sessions),
            "out_of_process_cli_calls": self.cli_calls,
            "sessions": [{"index": i, "image_sha256": s.executable_sha256,
                          "pid": None if s.process is None else s.process.pid,
                          "returncode": None if s.process is None else s.process.returncode}
                         for i, s in enumerate(self.sessions)],
            "generated_inputs": self.generated, "pipe_events": self.events,
            "files": [{"name": name, "bytes": (self.directory / name).stat().st_size,
                       "sha256": hashlib.sha256((self.directory / name).read_bytes()).hexdigest()}
                      for name in sorted(self.files)],
            "limitations": [
                "No extra archive-path reads: invalid paths, symlinks and FIFO inputs are not opened by capture.",
                "Recorded ZIP bytes are fixture generator outputs, not a claimed stable image of a concurrently changing file.",
                "Direct ZipFile fixtures retain member inputs, not a reconstructed byte-exact ZIP container.",
                "Owned-session pipes in this pytest process only; parent-death probe subprocess pipes remain in their existing pinned driver/report.",
                "No in-process session is not evidence of prelaunch rejection: out-of-process CLI and probe sessions are unobserved by this recorder.",
                "Successful export-analyze CLI calls can have unobserved input-core wire; CLI status does not supply those missing raw bytes.",
            ],
        }
        (self.directory / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


class SessionOS:
    """Module-local proxy: never monkeypatch the process-wide os module."""
    def __init__(self, capture):
        self.capture = capture

    def __getattr__(self, name):
        return getattr(os, name)

    def read(self, fd, size):
        data = os.read(fd, size)
        self.capture.transferred("read", fd, data)
        return data

    def write(self, fd, data):
        size = os.write(fd, data)
        self.capture.transferred("write", fd, data[:size])
        return size


def install(capture, monkeypatch, module):
    session_class = module.RustInputSession
    exchange = session_class._exchange
    def recorded_exchange(owner, *args, **kwargs):
        index = capture.session(owner)
        try:
            return exchange(owner, *args, **kwargs)
        except BaseException as error:
            capture.events.append({"session": index, "exception_type": type(error).__name__,
                                   "code": getattr(error, "code", None)})
            raise
    monkeypatch.setattr(session_class, "_exchange", recorded_exchange)
    monkeypatch.setattr(module.rust_input, "os", SessionOS(capture))
    command = module.command
    def recorded_command(*args, **kwargs):
        result = command(*args, **kwargs)
        try:
            capture.cli_calls.append({
                "command": str(args[0]), "exit_code": result[0],
                "input_core_wire": "unobserved_out_of_process",
                "raw_cli_stdout_stderr": "not_captured",
            })
        except BaseException as error:
            capture.failed("cli_scope_metadata", error)
            raise
        return result
    monkeypatch.setattr(module, "command", recorded_command)
    generate = module.zip_bytes
    def generated_zip(*args, **kwargs):
        raw = generate(*args, **kwargs)
        capture.fixture("zip", raw)
        return raw
    monkeypatch.setattr(module, "zip_bytes", generated_zip)
    write_bytes = Path.write_bytes
    def generated_archive_path(path, data):
        # Observe already-present fixture buffers at their write call, including
        # deliberately truncated/replacement archives. Never open a source path.
        if path.suffix in {".zip", ".new"}:
            capture.fixture("archive-write", data, fixture_basename=path.name)
        return write_bytes(path, data)
    monkeypatch.setattr(Path, "write_bytes", generated_archive_path)
    write_member = module.zipfile.ZipFile.writestr
    def generated_member(archive, name, data, *args, **kwargs):
        # Record only the caller-supplied fixture bytes. No file is reread.
        raw = data.encode("utf-8") if isinstance(data, str) else bytes(data)
        path = name.filename if isinstance(name, module.zipfile.ZipInfo) else name
        capture.fixture("zip-member", raw, member_name=path)
        return write_member(archive, name, data, *args, **kwargs)
    monkeypatch.setattr(module.zipfile.ZipFile, "writestr", generated_member)
